name: Create secret

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to deploy to'
        required: true
        default: 'dev'
      secret_name:
        description: 'Secret name'
        required: true
      secret_value:
        description: 'Secret value'
        required: true
      region:
        type: choice
        default: 'us-east-1'
        options:
          - us-east-1
          - us-east-2
          - us-west-1
          - us-west-2

env:
  SECRET_NAME: ${{ github.event.inputs.secret_name }}
  SECRET_VALUE: ${{ github.event.inputs.secret_value }}
  REGION: ${{ github.event.inputs.region }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to '${{ github.event.inputs.environment }}' environment"
      - run: echo "Secret name '${{ github.event.inputs.secret_name }}'"
      - run: echo "Secret value '${{ github.event.inputs.secret_value }}'"
